trigger:
  - main # or whichever branches you want to sync

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: github-sync-secrets # The name of your Variable Group

steps:
- checkout: self
  persistCredentials: true # Vital: Allows the script to use the AzDO token

- script: |
    git remote add github https://$(GitHub_PAT)@github.com/felixarchon/Macros.git

    git push github HEAD:main --force
  displayName: 'Sync main to GitHub'